# docker compose -f docker-compose-camila/docker-compose-be.yml up --build -d
# docker compose -f docker-compose-camila/docker-compose-be.yml down

version: '3.8'

services:
  visons-app:
    build:
      context: ..
      dockerfile: Dockerfile

    image: camila0814/mibackend:latest

    container_name: visons-backend-camila

    ports:
      - "9090:9090"

    environment:
      DB_URL: "jdbc:sqlserver://mssql-server:1433;databaseName=Visons;encrypt=true;trustServerCertificate=true"
      DB_USER: "sa"
      DB_PASSWORD: "Admin12345!"
      DB_DRIVER: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      SPRING_PROFILES_ACTIVE: "sqlserver"
      PORT: "9090"
      SERVER_PORT: "9090"
      SERVER_URL: "http://localhost:9090"

    networks:
      - visons-network

    restart: on-failure

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/swagger-ui.html"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

networks:
  visons-network:
    external: true
