# docker compose -f docker-compose-db.yml up -d
# docker compose -f docker-compose-db.yml down

services:
  mssql-server:
    image: diego5621/sql-server:2022-latest
    container_name: visons-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin12345!"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ../src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - visons-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Admin12345!", "-Q", "SELECT 1", "-No", "-C"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

volumes:
  mssql_data:
    driver: local

networks:
  visons-network:
    name: visons-network
    driver: bridge