FROM lizethquispesuarez/eclipse-temurin:25-jre-alpine

WORKDIR /app

# Copy the jar built on the host (parent project's target)
COPY ../target/*.jar app.jar

ENV PORT=8080

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
